# Generated by Django 4.1.1 on 2022-10-01 08:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(default='default post', max_length=50)),
                ('description', models.TextField(default='the description of the post')),
                ('date_create', models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 23, 45, 266762, tzinfo=datetime.timezone.utc))),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee description',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('priority_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='default code', max_length=50)),
                ('name', models.CharField(default='default name', max_length=40)),
                ('description', models.TextField(default='')),
                ('date_create', models.DateField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priority description',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='hello_world', max_length=50)),
                ('description', models.TextField(default='description of the project')),
                ('date_create', models.DateField(auto_now=True)),
                ('code', models.CharField(default='default code', max_length=50)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project description',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='default code', max_length=50)),
                ('date_create', models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 23, 45, 265763, tzinfo=datetime.timezone.utc))),
                ('name', models.CharField(default='hello_world', max_length=50)),
                ('isClosed', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'State description',
            },
        ),
        migrations.CreateModel(
            name='TypeTask',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='default code', max_length=50)),
                ('name', models.CharField(default='default name', max_length=40)),
                ('description', models.TextField(default='')),
                ('date_create', models.DateField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Type description',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='default code', max_length=50)),
                ('name', models.CharField(default='default name', max_length=50)),
                ('description', models.TextField(blank=True, default='description of the task')),
                ('date_create', models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 23, 45, 266762, tzinfo=datetime.timezone.utc))),
                ('date_change', models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 23, 45, 266762, tzinfo=datetime.timezone.utc))),
                ('date_deadline', models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 23, 45, 266762, tzinfo=datetime.timezone.utc))),
                ('is_activate', models.BooleanField(default=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr', to='tracking_dev.employee')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrrr', to='tracking_dev.priority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrrrrr', to='tracking_dev.project')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r', to='tracking_dev.employee')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrr', to='tracking_dev.state')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrrrr', to='tracking_dev.typetask')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task description',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(related_name='employee_projects', to='tracking_dev.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
