# Generated by Django 4.1.1 on 2022-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='hello_world', max_length=50)),
                ('description', models.TextField(default='description of the project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project description',
            },
        ),
    ]
