# Generated by Django 4.1.1 on 2022-09-11 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0002_alter_project_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 11, 9, 46, 16, 909806, tzinfo=datetime.timezone.utc)),
        ),
    ]
