# Generated by Django 4.1.1 on 2022-09-11 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0003_project_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='default code', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 11, 10, 52, 44, 139365, tzinfo=datetime.timezone.utc)),
        ),
    ]
