# Generated by Django 4.1.1 on 2022-09-15 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0004_project_code_alter_project_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='hello_world', max_length=50)),
                ('isClosed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'State description',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 15, 10, 52, 57, 808100, tzinfo=datetime.timezone.utc)),
        ),
    ]
