# Generated by Django 4.1.1 on 2022-09-15 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0005_state_alter_project_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(default='default code', max_length=50),
        ),
        migrations.AddField(
            model_name='state',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 15, 11, 46, 48, 899835, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 15, 11, 46, 48, 899835, tzinfo=datetime.timezone.utc)),
        ),
    ]
