# Generated by Django 4.1.1 on 2022-09-15 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0006_state_code_state_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 15, 11, 51, 38, 903685, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 15, 11, 51, 38, 903685, tzinfo=datetime.timezone.utc)),
        ),
    ]
