# Generated by Django 4.1.1 on 2022-10-01 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0007_alter_employee_date_create_alter_state_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='some_field',
            field=models.CharField(default='foo', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 24, 57, 146424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 24, 57, 146424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_change',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 24, 57, 147424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 24, 57, 147424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 24, 57, 147424, tzinfo=datetime.timezone.utc)),
        ),
    ]
