# Generated by Django 4.1.1 on 2022-09-17 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0007_state_description_alter_project_date_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('priority_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='default code', max_length=50)),
                ('name', models.CharField(default='default name', max_length=40)),
                ('description', models.TextField(default='')),
                ('date_create', models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 6, 33, 58, 29356, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priority description',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 6, 33, 58, 28355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 6, 33, 58, 29356, tzinfo=datetime.timezone.utc)),
        ),
    ]
