# Generated by Django 4.1.1 on 2022-09-17 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0008_priority_alter_project_date_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTask',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='default code', max_length=50)),
                ('name', models.CharField(default='default name', max_length=40)),
                ('description', models.TextField(default='')),
                ('date_create', models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 7, 30, 15, 575219, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Type description',
            },
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 7, 30, 15, 575219, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 7, 30, 15, 575219, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 7, 30, 15, 575219, tzinfo=datetime.timezone.utc)),
        ),
    ]
