# Generated by Django 4.1.1 on 2022-10-01 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0009_remove_task_some_field_alter_employee_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrrrrrr', to='tracking_dev.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 26, 35, 568361, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 26, 35, 568361, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_change',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 26, 35, 569355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 26, 35, 569355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 1, 8, 26, 35, 569355, tzinfo=datetime.timezone.utc)),
        ),
    ]
