# Generated by Django 4.1.1 on 2022-10-22 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0014_alter_employee_date_create_alter_project_date_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 22, 6, 58, 12, 350466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 22, 6, 58, 12, 350466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 22, 6, 58, 12, 350466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_change',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 22, 6, 58, 12, 350466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 22, 6, 58, 12, 350466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 22, 6, 58, 12, 350466, tzinfo=datetime.timezone.utc)),
        ),
    ]
