# Generated by Django 4.1.1 on 2022-09-17 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0015_alter_employee_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 10, 43, 57, 373611, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 10, 43, 57, 372611, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 10, 43, 57, 372611, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 10, 43, 57, 372611, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 10, 43, 57, 373611, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='default code', max_length=50)),
                ('name', models.CharField(default='default name', max_length=50)),
                ('description', models.TextField(blank=True, default='description of the task')),
                ('date_create', models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 10, 43, 57, 373611, tzinfo=datetime.timezone.utc))),
                ('date_change', models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 10, 43, 57, 373611, tzinfo=datetime.timezone.utc))),
                ('date_deadline', models.DateField(blank=True, default=datetime.datetime(2022, 9, 17, 10, 43, 57, 373611, tzinfo=datetime.timezone.utc))),
                ('initiator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rr', to='tracking_dev.employee')),
                ('priority', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rrrr', to='tracking_dev.priority')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rrrrrr', to='tracking_dev.project')),
                ('responsible', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r', to='tracking_dev.employee')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rrr', to='tracking_dev.state')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rrrrr', to='tracking_dev.typetask')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task description',
            },
        ),
    ]
