# Generated by Django 4.1.1 on 2022-10-22 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0015_alter_employee_date_create_alter_project_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='priority',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typetask',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 22, 7, 8, 3, 693739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 22, 7, 8, 3, 693739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 22, 7, 8, 3, 692739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 22, 7, 8, 3, 693739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 22, 7, 8, 3, 694739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 22, 7, 8, 3, 694739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 22, 7, 8, 3, 693739, tzinfo=datetime.timezone.utc)),
        ),
    ]
