# Generated by Django 4.1.1 on 2022-11-01 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0016_employee_date_change_priority_date_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 14, 38, 34, 805712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 1, 14, 38, 34, 805712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 14, 38, 34, 804712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 14, 38, 34, 804712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 14, 38, 34, 806712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 1, 14, 38, 34, 806712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 14, 38, 34, 805712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SubTasks',
            fields=[
                ('sub_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_task_description', to='tracking_dev.task')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_task_id', to='tracking_dev.task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task description',
            },
        ),
    ]
