# Generated by Django 4.1.1 on 2022-11-12 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0018_rename_reference_task_id_subtasks_reference_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 31, 11, 883305, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 31, 11, 882304, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 31, 11, 881304, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 31, 11, 882304, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 31, 11, 883305, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 31, 11, 883305, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 31, 11, 882304, tzinfo=datetime.timezone.utc)),
        ),
    ]
