# Generated by Django 4.1.1 on 2022-09-24 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0022_alter_employee_date_create_alter_state_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 24, 8, 38, 11, 641189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='is_activate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 24, 8, 38, 11, 641189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_change',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 24, 8, 38, 11, 642187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 24, 8, 38, 11, 642187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 24, 8, 38, 11, 642187, tzinfo=datetime.timezone.utc)),
        ),
    ]
