# Generated by Django 4.1.1 on 2022-11-12 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0023_alter_employee_date_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('sprint_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='default code', max_length=50)),
                ('name', models.CharField(default='default name', max_length=50)),
                ('description', models.TextField(blank=True, default='description of the task')),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 34, 27, 349866, tzinfo=datetime.timezone.utc))),
                ('date_start', models.DateTimeField(default=datetime.datetime(2022, 11, 12, 6, 34, 27, 349866, tzinfo=datetime.timezone.utc))),
                ('date_end', models.DateTimeField(default=datetime.datetime(2022, 11, 12, 6, 34, 27, 349866, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprint description',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 34, 27, 347867, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 34, 27, 347867, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 34, 27, 346866, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 34, 27, 347867, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 34, 27, 348866, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 34, 27, 348866, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 34, 27, 347867, tzinfo=datetime.timezone.utc)),
        ),
    ]
