# Generated by Django 4.1.1 on 2022-11-12 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0024_sprint_alter_employee_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='project_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='r_project_id', to='tracking_dev.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 42, 52, 242401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 42, 52, 242401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 42, 52, 241401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 42, 52, 244401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 6, 42, 52, 244401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 6, 42, 52, 244401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 42, 52, 241401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 42, 52, 243401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 42, 52, 243401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 6, 42, 52, 242401, tzinfo=datetime.timezone.utc)),
        ),
    ]
