# Generated by Django 4.1.1 on 2023-01-15 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0029_task_employee_alter_employee_date_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime(2023, 1, 15, 9, 27, 36, 365728, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Vote description',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 9, 27, 36, 364729, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 15, 9, 27, 36, 363728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 9, 27, 36, 363728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 9, 27, 36, 365728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 9, 27, 36, 365728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 9, 27, 36, 365728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 9, 27, 36, 363728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 9, 27, 36, 364729, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 15, 9, 27, 36, 364729, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 9, 27, 36, 364729, tzinfo=datetime.timezone.utc)),
        ),
    ]
