# Generated by Django 4.1.1 on 2023-01-18 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0031_delete_vote_alter_employee_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 18, 7, 15, 41, 280210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 18, 7, 15, 41, 280210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 18, 7, 15, 41, 279210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 18, 7, 15, 41, 282210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 7, 15, 41, 282210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 7, 15, 41, 282210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 18, 7, 15, 41, 279210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 18, 7, 15, 41, 281210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 18, 7, 15, 41, 281210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 18, 7, 15, 41, 280210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Laboriousness',
            fields=[
                ('laboriousness_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity_plan', models.IntegerField(default=0)),
                ('fact_plan', models.IntegerField(default=0)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_employee_id', to='tracking_dev.employee')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_task_id', to='tracking_dev.task')),
            ],
            options={
                'verbose_name': 'Laboriousness',
                'verbose_name_plural': 'Laboriousness description',
            },
        ),
    ]
