# Generated by Django 4.1.1 on 2023-02-12 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0038_state_projects_alter_employee_date_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='something', max_length=50)),
                ('description', models.TextField(default='description of the text')),
                ('salary', models.IntegerField(default=0)),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 13, 58, 4, 215557, tzinfo=datetime.timezone.utc))),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Profession description',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 13, 58, 4, 217557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 12, 13, 58, 4, 216557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 13, 58, 4, 215557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 13, 58, 4, 219556, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 13, 58, 4, 219556, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 13, 58, 4, 219556, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 13, 58, 4, 216557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 13, 58, 4, 218556, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 12, 13, 58, 4, 218556, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 13, 58, 4, 217557, tzinfo=datetime.timezone.utc)),
        ),
    ]
