# Generated by Django 4.1.1 on 2023-02-18 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0040_profession_code_alter_employee_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profession',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profession', to='tracking_dev.profession'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 18, 13, 58, 49, 843261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 18, 13, 58, 49, 842261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profession',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 18, 13, 58, 49, 841261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 18, 13, 58, 49, 841261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 18, 13, 58, 49, 845261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 13, 58, 49, 845261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 13, 58, 49, 845261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 18, 13, 58, 49, 842261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 18, 13, 58, 49, 844261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 18, 13, 58, 49, 844261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 18, 13, 58, 49, 843261, tzinfo=datetime.timezone.utc)),
        ),
    ]
