# Generated by Django 4.1.1 on 2023-04-02 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0044_priority_priority_color_alter_employee_date_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Project description'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='date_deadline',
            field=models.DateField(default=datetime.datetime(2023, 4, 2, 7, 4, 15, 57765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='laboriousness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 4, 15, 57765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 4, 15, 59765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profession',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 4, 15, 57765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 4, 15, 57765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 4, 15, 61764, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 7, 4, 15, 61764, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 7, 4, 15, 61764, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 4, 15, 58765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 4, 15, 60764, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 4, 15, 60764, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 4, 15, 59765, tzinfo=datetime.timezone.utc)),
        ),
    ]
