# Generated by Django 4.1.1 on 2023-04-02 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_dev', '0045_alter_employee_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='post',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 8, 35, 21, 989185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='priority',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 2, 8, 35, 21, 990185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profession',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 8, 35, 21, 988185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 8, 35, 21, 989185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_deadline',
            field=models.DateField(default=datetime.datetime(2023, 4, 2, 8, 35, 21, 989185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 8, 35, 21, 993185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 8, 35, 21, 993185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 8, 35, 21, 993185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 8, 35, 21, 990185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 8, 35, 21, 991187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 2, 8, 35, 21, 991187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 8, 35, 21, 991187, tzinfo=datetime.timezone.utc)),
        ),
    ]
